import os
import re

SLACK_TOKEN = os.getenv('SLACK_BOT_TOKEN')
BOT_USER_NAME = os.getenv('SLACK_BOT_NAME', 'giphy-sucks-bot')
BOT_USER_ID = os.getenv('SLACK_BOT_ID', 'U2JSMBG74')

FAIL_REGEX = [
    "fail",
    "nope",
    "you tried",
    "try again",
    "wh?at",
    "uh+",
    "come on",
    "c'?mon",
    "suck",
    "fuck",
    "worst",
    "awful",
    "bad",
    "terrible",
    "not good",
    "dumb"
]

SUCKS_REGEX = [
    "suck",
    "fuck",
    "worst",
    "awful",
    "bad",
    "terrible",
    "not good",
    "dumb",
    "useless",
    ""
]

FAIL_REGEX = "(%s)" % ('|'.join(FAIL_REGEX))
FAIL_REGEX = re.compile(FAIL_REGEX, re.IGNORECASE)


SUCKS_REGEX = "(%s)" % ('|'.join(SUCKS_REGEX))
SUCKS_REGEX = re.compile(SUCKS_REGEX, re.IGNORECASE)

FAIL_MESSAGES = [
    "giphy_irl %s",
    "meanwhile, in the giphy offices... %s",
    "you had literally one job",
    "this is why we can't have nice things",
    "see!  this is what I'm talking about!",
    "rare footage of giphy in action %s",
    "well that backfired"
]

SUCKS_MESSAGES = [
    "this guy gets it",
    "that's what I'm saying!",
    "and this is news?",
    "agreed.",
    "this.",
    "couldn't have put it any better myself"


]

FAIL_IMAGES = [
    "https://media2.giphy.com/media/l0HlQkCyeHCKmLIWs/giphy.gif",
    "https://media3.giphy.com/media/l0OWiMGpoC6apZFXG/giphy.gif",
    "https://media3.giphy.com/media/xEtLay2J994s0/giphy.gif",
    "https://media2.giphy.com/media/l0MYWEZ36MOAEAkq4/giphy.gif",
    "https://media1.giphy.com/media/JTmt4C8AjGzxm/giphy.gif",
    "https://media4.giphy.com/media/xTiTncVep2khPGhK1i/giphy.gif",
    "https://media4.giphy.com/media/3oEdv1uvUApQeiXpU4/giphy.gif",
    "https://media1.giphy.com/media/26h0pUuVl7IpjTfsA/giphy.gif",
    "https://media4.giphy.com/media/l41lVeOK1d4Fg7PW0/giphy.gif",
    "https://media3.giphy.com/media/XpPhTXkmXpsg8/giphy.gif",
    "https://media4.giphy.com/media/26tOZxcbcZzxDlek8/giphy.gif",
    "https://media0.giphy.com/media/WghwyziDDfR4s/giphy.gif",
    "https://media0.giphy.com/media/26tP41fh76vmLO3iU/giphy.gif",
    "https://media0.giphy.com/media/13E2uKO2hcHLHi/giphy.gif",
    "https://media3.giphy.com/media/3o6Zt1TrXW8uW2lE2I/giphy.gif",
    "https://media4.giphy.com/media/47KjwlPVpnQOs/giphy.gif",
    "https://media0.giphy.com/media/nwAhNBiaVinVm/giphy.gif",
    "https://media4.giphy.com/media/3o7TKPIg3kpnhhUEZG/giphy.gif",
    "https://media0.giphy.com/media/l0MYN32Z3gLPHlXry/giphy.gif",
    "https://media2.giphy.com/media/3o7ZesJdQccI0sO3fy/giphy.gif",
    "https://media4.giphy.com/media/3o8doVAxrMjXbIHaU0/giphy.gif",
    "https://media2.giphy.com/media/FIVuMAMJuwPks/giphy.gif",
    "https://media0.giphy.com/media/z75PUpyuVxcxa/giphy.gif",
    "https://media2.giphy.com/media/l41m2CdrZUCtgtXWg/giphy.gif",
    "https://media2.giphy.com/media/F9AU77Krzw8ta/giphy.gif",
    "https://media1.giphy.com/media/3ornjU8Cd8FW1nhG6s/giphy.gif",
    "https://media4.giphy.com/media/9lEeDMb6LXfvG/giphy.gif",
    "https://media1.giphy.com/media/YgecHlkucOGGY/giphy.gif",
    "https://media1.giphy.com/media/l0HlLO5kE2kOZivew/giphy.gif",
    "https://media2.giphy.com/media/3oEduF28OYY6D6Gg0g/giphy.gif",
    "https://media0.giphy.com/media/7mMRX7gWzDVwA/giphy.gif",
    "https://media4.giphy.com/media/TuhRXzq9pAOg8/giphy.gif",
    "https://media0.giphy.com/media/WuwAllkYBgQCI/giphy.gif",
    "https://media0.giphy.com/media/26uf1w19JaA9wpElO/giphy.gif",
    "https://media4.giphy.com/media/3o7rc0N1lGLO9dUAz6/giphy.gif",
    "https://media0.giphy.com/media/g2qW795KmuqSk/giphy.gif",
    "https://media3.giphy.com/media/l3fQuB4uo1h17XEOc/giphy.gif",
    "https://media3.giphy.com/media/l41YibYRTTfN00OWc/giphy.gif",
    "https://media1.giphy.com/media/57WEsxpUr3bTG/giphy.gif",
    "https://media4.giphy.com/media/3oEjHG1n0KwFz4hcC4/giphy.gif",
    "https://media2.giphy.com/media/9ZvFhDkaAfyLe/giphy.gif",
    "https://media1.giphy.com/media/pg947vU6PFUD6/giphy.gif",
    "https://media1.giphy.com/media/MQEBfbPco0fao/giphy.gif",
    "https://media0.giphy.com/media/lo5jV0hLNr7Gw/giphy.gif",
    "https://media1.giphy.com/media/3owypf6HrM3J7UTvAA/giphy.gif",
    "https://media1.giphy.com/media/uRcoPXfNZUMp2/giphy.gif",
    "https://media4.giphy.com/media/3o72F0Tw20TgC9t720/giphy.gif",
    "https://media4.giphy.com/media/ABoaCMjkoqmIg/giphy.gif",
    "https://media1.giphy.com/media/QKKV7KFrG9XMY/giphy.gif",
    "https://media3.giphy.com/media/lj11uKKMhr4Os/giphy.gif",
    "https://media2.giphy.com/media/I7kkegrRyNrk4/giphy.gif",
    "https://media3.giphy.com/media/3o6ZsXAElDtzalJcZy/giphy.gif",
    "https://media3.giphy.com/media/WOzEogVqHibvO/giphy.gif",
    "https://media3.giphy.com/media/3o7TKv7xq9Be7y2wq4/giphy.gif",
    "https://media4.giphy.com/media/123SNNIIuScdTW/giphy.gif",
    "https://media1.giphy.com/media/l2R0bByKRZ0Lv4vxm/giphy.gif",
    "https://media3.giphy.com/media/vyfNVia1rW0nK/giphy.gif",
    "https://media1.giphy.com/media/a2ikRiPG0RDTW/giphy.gif",
    "https://media3.giphy.com/media/g8CJl0epg71MQ/giphy.gif",
    "https://media2.giphy.com/media/l3V0tBWypnEj0DfVe/giphy.gif",
    "https://media1.giphy.com/media/QIfrzL8m2zAYw/giphy.gif",
    "https://media4.giphy.com/media/3o85xxSZvFZgD4wXde/giphy.gif",
    "https://media3.giphy.com/media/5FhJdxmOCCIXm/giphy.gif",
    "https://media4.giphy.com/media/3o8doTsfXIV3ZTHA76/giphy.gif",
    "https://media3.giphy.com/media/3osxYwS1I1pxvgY8g0/giphy.gif",
    "https://media1.giphy.com/media/jkpVaBMVt0ZfW/giphy.gif",
    "https://media2.giphy.com/media/3o6ozoD2BgEK8KNtfi/giphy.gif",
    "https://media0.giphy.com/media/vDq50EPOSGYHm/giphy.gif",
    "https://media2.giphy.com/media/hUfIkiSJYnxDy/giphy.gif",
    "https://media3.giphy.com/media/OIZMv49aoUGLS/giphy.gif",
    "https://media2.giphy.com/media/Q8OIR3s0hT5p6/giphy.gif",
    "https://media1.giphy.com/media/adO9k9luhr8vC/giphy.gif",
    "https://media4.giphy.com/media/26tOVXZALFoZdJ42I/giphy.gif",
    "https://media3.giphy.com/media/l4KibWpBGWchSqCRy/giphy.gif",
    "https://media0.giphy.com/media/3oEduMifrXVBDOX0k0/giphy.gif",
    "https://media3.giphy.com/media/l41lR9cLxFqcJI4co/giphy.gif",
    "https://media1.giphy.com/media/l41lIioP4RFRmIVB6/giphy.gif",
    "https://media1.giphy.com/media/3oEdvanlXvozVLoIqQ/giphy.gif",
    "https://media3.giphy.com/media/13jAs8c6rIkz0Q/giphy.gif",
    "https://media3.giphy.com/media/3oEjHV41TSKaSW7FtK/giphy.gif",
    "https://media0.giphy.com/media/26FPLsoMq5cPEVgg8/giphy.gif",
    "https://media2.giphy.com/media/3osxY4boRWYwg1VVZe/giphy.gif",
    "https://media3.giphy.com/media/l2R04CaebgtebcxvG/giphy.gif",
    "https://media2.giphy.com/media/l0NwSuQkSvAsjJsAg/giphy.gif",
    "https://media2.giphy.com/media/3osxYBaAo7NG5GjNAs/giphy.gif",
    "https://media3.giphy.com/media/l2QZWezJwk5gaeuxq/giphy.gif",
    "https://media2.giphy.com/media/3osxYmmfEW246r6d0c/giphy.gif",
    "https://media0.giphy.com/media/3o7Zez01HKXvaLXiHS/giphy.gif",
    "https://media1.giphy.com/media/3o7rc2y7avp4SNXG9O/giphy.gif",
    "https://media3.giphy.com/media/3o7rbX87Xv4fa4fDO0/giphy.gif",
    "https://media0.giphy.com/media/3oxRmGNqKwCzJ0AwPC/giphy.gif",
    "https://media1.giphy.com/media/xYRvkBcJhbSr6/giphy.gif",
    "https://media1.giphy.com/media/3o85xz8c70Ba4W8TCg/giphy.gif",
    "https://media4.giphy.com/media/EfZL4ASoIiPLy/giphy.gif",
    "https://media0.giphy.com/media/m9QaesHUwTT4A/giphy.gif",
    "https://media0.giphy.com/media/EIbk2OkbydMoo/giphy.gif",
    "https://media1.giphy.com/media/QuERhU4cK83V6/giphy.gif",
    "https://media1.giphy.com/media/tsIFjie7obBM4/giphy.gif",
    "https://media4.giphy.com/media/3o85xjWCl9EVJOCULK/giphy.gif",
    "https://media1.giphy.com/media/nKN7E76a27Uek/giphy.gif",
    "https://media2.giphy.com/media/xTiTnvyOryUz4apuH6/giphy.gif",
    "https://media0.giphy.com/media/KmlTchPoFQT84/giphy.gif",
    "https://media3.giphy.com/media/SPPL9l9KZGoFO/giphy.gif",
    "https://media2.giphy.com/media/3osxYmPBt9PMatfkl2/giphy.gif",
    "https://media0.giphy.com/media/MX8U85OiO1g7S/giphy.gif",
    "https://media0.giphy.com/media/LI7DRrJeN0dIk/giphy.gif",
    "https://media0.giphy.com/media/JNgLZn7fWAjjW/giphy.gif",
    "https://media1.giphy.com/media/FGyywmWE7q7rW/giphy.gif",
    "https://media2.giphy.com/media/RDuF5FVTSyzy8/giphy.gif",
    "https://media2.giphy.com/media/HrydPrw0zphAs/giphy.gif",
    "https://media1.giphy.com/media/3o85xLDcbiw2Gy7evu/giphy.gif",
    "https://media4.giphy.com/media/3o85xLdJW6l1VDyvHq/giphy.gif",
    "https://media2.giphy.com/media/3o85xAhajhREONa5wI/giphy.gif",
    "https://media2.giphy.com/media/AAnIjZPUhrUM8/giphy.gif",
    "https://media1.giphy.com/media/zYd90i773lLoc/giphy.gif",
    "https://media2.giphy.com/media/aI3IA8BVUCbPa/giphy.gif",
    "https://media1.giphy.com/media/xTiTnLbo0KIJ8hrNjG/giphy.gif",
    "https://media2.giphy.com/media/l0O9yanlMYzLFoa4M/giphy.gif",
    "https://media3.giphy.com/media/26tP6sQx9G4B1kagE/giphy.gif",
    "https://media4.giphy.com/media/xTiTnMiq5LRFrygYNO/giphy.gif",
    "https://media3.giphy.com/media/26FPGsG2NZL1QzAFW/giphy.gif",
    "https://media2.giphy.com/media/3o7ZexFSShwaxOSY12/giphy.gif",
    "https://media2.giphy.com/media/xTk9ZH5U5vb76JhNHa/giphy.gif",
    "https://media1.giphy.com/media/26tP972jcNs3V4bKw/giphy.gif",
    "https://media1.giphy.com/media/3oEduKP4VaUxJvLwuA/giphy.gif",
    "https://media2.giphy.com/media/26tPhNJomQlAbEBy0/giphy.gif",
    "https://media0.giphy.com/media/l2QZQPqIgeFAfZLDa/giphy.gif",
    "https://media0.giphy.com/media/xTiTnFbwkFLI7q1eDu/giphy.gif",
    "https://media0.giphy.com/media/xTiTnuQhFgCMORAGGY/giphy.gif",
    "https://media0.giphy.com/media/l2QZWlQlPoWAPqi9G/giphy.gif",
    "https://media0.giphy.com/media/l0NwuvFERvrjszjd6/giphy.gif",
    "https://media4.giphy.com/media/d2ZafgYFc4NHaTg4/giphy.gif",
    "https://media2.giphy.com/media/PqdfIrXEza6fC/giphy.gif",
    "https://media4.giphy.com/media/xTk9ZUb96JJueUfmCI/giphy.gif",
    "https://media2.giphy.com/media/xTk9ZzD6NuYrMuDBx6/giphy.gif",
    "https://media1.giphy.com/media/l41lPaVXzvGGMuAQ8/giphy.gif",
    "https://media1.giphy.com/media/l41lKy6p2jDMyHuDe/giphy.gif",
    "https://media2.giphy.com/media/3o85xI2puiISvwEDx6/giphy.gif",
    "https://media0.giphy.com/media/3o85xB4Dgz1QtnKDiE/giphy.gif",
    "https://media2.giphy.com/media/3oEduEvByabo6QTgLm/giphy.gif",
    "https://media0.giphy.com/media/jWnzTZrpXOgmI/giphy.gif",
    "https://media2.giphy.com/media/12GB4AQYzwfIha/giphy.gif",
    "https://media3.giphy.com/media/xT8qAYK2m79N91ikzm/giphy.gif",
    "https://media3.giphy.com/media/JQFim1Fzt6048/giphy.gif",
    "https://media0.giphy.com/media/26xoplW0VhLLByrAY/giphy.gif",
    "https://media1.giphy.com/media/JLuTANgVdrgyI/giphy.gif",
    "https://media2.giphy.com/media/3oEdv2CrA48J1wi3i8/giphy.gif",
    "https://media2.giphy.com/media/l46CeXx4PaMaG54E8/giphy.gif",
    "https://media0.giphy.com/media/cS83sLRzgVOeY/giphy.gif",
    "https://media1.giphy.com/media/xT8qB0yWb2R5Cvv1kI/200.gif",
    "https://media2.giphy.com/media/Pnph2o2G5pfkA/200.gif",
    "https://media4.giphy.com/media/3o7WTruI0WvGZ8jLgs/200w.gif",
    "https://media3.giphy.com/media/1GMayb1ub8XQc/200.gif",
    "https://media0.giphy.com/media/V0sDfHNMkBdNm/200.gif",
    "https://media3.giphy.com/media/dBHyy0gA87NTy/200.gif",
    "https://media3.giphy.com/media/3o7qEcmgf2wBmVAteU/200.gif",
    "https://media2.giphy.com/media/l3UcxAzPSRNSedfhK/200.gif",
    "https://media4.giphy.com/media/l3Ucwud2SU0iHTRHa/200.gif",
    "https://media3.giphy.com/media/l2JJHMSGcDTDd8go0/200.gif",
    "https://media3.giphy.com/media/3osxYhufvkO5dz9jSo/200.gif",
    "https://media1.giphy.com/media/l4KhKwYNat8Z6KAaQ/200.gif",
    "https://media2.giphy.com/media/xTcnSPG2Hw51P6Uhjy/200.gif",
    "https://media3.giphy.com/media/l0O9x4lh4wvUEKPi8/200.gif",
    "https://media4.giphy.com/media/m3aNn7GrkjiLe/giphy.gif",
    "https://media1.giphy.com/media/CIspSkUM7KtDq/giphy.gif",
    "https://media1.giphy.com/media/CDHWRPhoycqJO/giphy.gif",
    "https://media0.giphy.com/media/l0K4kMpIH7aFUPt3a/giphy.gif",
    "https://media3.giphy.com/media/pcC2u7rl89b44/giphy.gif",
    "https://media2.giphy.com/media/ucKrOzkKyu6B2/giphy.gif",
    "https://media3.giphy.com/media/3oEjHVtFOfQKzqG8ms/giphy.gif",
    "https://media0.giphy.com/media/10QmFpzwECH0mA/giphy.gif",
    "https://media3.giphy.com/media/Jd5YlXOVTcQtW/giphy.gif"
]